title: Learn AI - Deep Learning solutions using Text Analytics ToolKit
description: Microsoft labs for building Deep Learning solutions using Text Analytics ToolKit
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomTextAnalyticsWithAML