title: Learn AI - Building Custom Text Analytics solutions using AML
description: Microsoft labs for building Building Custom Text Analytics solutions using Azure MAchine Learning
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomTextAnalyticsWithAML
